[package]
name = "r-shell"
version = "2.1.0"
edition = "2024"

[[bin]]
name = "r-shell"
path = "src/main.rs"

[dependencies]
r-shell-core = { path = "../core" }
anyhow = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
