// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 用配对码与设备配对(`adb pair <host:port> <code>`)。
///
/// `host_port` 是手机「无线调试 → 使用配对码配对设备」里显示的**配对地址**
/// (端口随机,不是 5555);`code` 是同一界面的 6 位配对码。返回 adb 的成功提示。
Future<String> adbPair({required String hostPort, required String code}) =>
    RustLib.instance.api.crateApiAdbAdbPair(hostPort: hostPort, code: code);

/// 连接网络 adb 设备(`adb connect <host:port>`,通常端口 5555)。返回 adb 的提示。
Future<String> adbConnect({required String hostPort}) =>
    RustLib.instance.api.crateApiAdbAdbConnect(hostPort: hostPort);
