// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// 在某已保存连接(SSH / ADB)上执行一条命令块。
///
/// `cwd` 为上一块结束时的工作目录(首次传空串,由远端默认目录回填)。
Future<BlockResultDto> blockRunRemote({
  required String connectionId,
  required String command,
  required String cwd,
}) => RustLib.instance.api.crateApiBlocktermBlockRunRemote(
  connectionId: connectionId,
  command: command,
  cwd: cwd,
);

/// 在本机(运行 GUI 的电脑)执行一条命令块。
Future<BlockResultDto> blockRunLocal({
  required String command,
  required String cwd,
}) => RustLib.instance.api.crateApiBlocktermBlockRunLocal(
  command: command,
  cwd: cwd,
);

/// 一条命令块的执行结果(frb 友好的 DTO,与 core [`BlockOutcome`] 一一映射)。
class BlockResultDto {
  /// 合并后的输出(stdout+stderr),已剥离哨兵尾巴。
  final String body;

  /// 用户命令退出码;未命中哨兵(非 POSIX 远端)时为 `-1`。
  final int exitCode;

  /// 命令结束后的工作目录(供下一块沿用)。
  final String cwd;

  /// 退出码 / cwd 是否可信(是否解析到哨兵)。
  final bool hadMarker;

  const BlockResultDto({
    required this.body,
    required this.exitCode,
    required this.cwd,
    required this.hadMarker,
  });

  @override
  int get hashCode =>
      body.hashCode ^ exitCode.hashCode ^ cwd.hashCode ^ hadMarker.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockResultDto &&
          runtimeType == other.runtimeType &&
          body == other.body &&
          exitCode == other.exitCode &&
          cwd == other.cwd &&
          hadMarker == other.hadMarker;
}
