// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_saved`

/// 读取本地 `workspace.json`，返回脱敏后的连接列表（分组信息在 `folder` 字段）。
List<ConnectionDto> listConnections() =>
    RustLib.instance.api.crateApiConnectionsListConnections();

/// 新建连接并写入 `workspace.json`，返回脱敏后的结果（含新生成的 id）。
ConnectionDto createConnection({required ConnectionInput input}) =>
    RustLib.instance.api.crateApiConnectionsCreateConnection(input: input);

/// 按 id 更新连接（提交整张表单），返回脱敏后的最新值。
ConnectionDto updateConnection({
  required String id,
  required ConnectionInput input,
}) => RustLib.instance.api.crateApiConnectionsUpdateConnection(
  id: id,
  input: input,
);

/// 按 id 删除连接（同时清理其终端标签与 active 指针）。
void deleteConnection({required String id}) =>
    RustLib.instance.api.crateApiConnectionsDeleteConnection(id: id);

/// 脱敏的连接信息（供 GUI 展示）。
///
/// **绝不包含明文密码 / 私钥内容 / passphrase** —— 只用布尔标记是否已配置，
/// 与 core 的 `SavedConnection::sanitized()` 策略保持一致。
class ConnectionDto {
  final String id;

  /// "SSH" | "ADB"
  final String protocol;
  final String name;
  final String host;
  final int port;
  final String username;
  final String folder;
  final String description;

  /// "password" | "publickey"
  final String authMethod;

  /// "Disconnected" | "Connecting" | "Connected"
  final String status;
  final List<String> tags;
  final bool hasPassword;
  final bool hasPrivateKeyPath;
  final bool hasPassphrase;

  const ConnectionDto({
    required this.id,
    required this.protocol,
    required this.name,
    required this.host,
    required this.port,
    required this.username,
    required this.folder,
    required this.description,
    required this.authMethod,
    required this.status,
    required this.tags,
    required this.hasPassword,
    required this.hasPrivateKeyPath,
    required this.hasPassphrase,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      protocol.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      folder.hashCode ^
      description.hashCode ^
      authMethod.hashCode ^
      status.hashCode ^
      tags.hashCode ^
      hasPassword.hashCode ^
      hasPrivateKeyPath.hashCode ^
      hasPassphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          protocol == other.protocol &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          folder == other.folder &&
          description == other.description &&
          authMethod == other.authMethod &&
          status == other.status &&
          tags == other.tags &&
          hasPassword == other.hasPassword &&
          hasPrivateKeyPath == other.hasPrivateKeyPath &&
          hasPassphrase == other.hasPassphrase;
}

/// 连接编辑表单的输入（创建 / 更新共用）。
///
/// 三个密钥字段的语义（与 `r_shell_core::connections::ConnectionPatch` 对齐）：
/// - `None`   —— 更新时保持原值不变；创建时表示「未设置」。
/// - `Some("")` —— 清除已保存的值。
/// - `Some(v)`  —— 设置为 `v`。
class ConnectionInput {
  /// "SSH"（默认）| "ADB"。
  final String protocol;
  final String name;
  final String host;
  final String username;
  final int port;

  /// "password" | "publickey"（其它值会被归一化为 "password"）。
  final String authMethod;
  final String folder;
  final String description;
  final List<String> tags;
  final String? password;
  final String? privateKeyPath;
  final String? passphrase;

  const ConnectionInput({
    required this.protocol,
    required this.name,
    required this.host,
    required this.username,
    required this.port,
    required this.authMethod,
    required this.folder,
    required this.description,
    required this.tags,
    this.password,
    this.privateKeyPath,
    this.passphrase,
  });

  @override
  int get hashCode =>
      protocol.hashCode ^
      name.hashCode ^
      host.hashCode ^
      username.hashCode ^
      port.hashCode ^
      authMethod.hashCode ^
      folder.hashCode ^
      description.hashCode ^
      tags.hashCode ^
      password.hashCode ^
      privateKeyPath.hashCode ^
      passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionInput &&
          runtimeType == other.runtimeType &&
          protocol == other.protocol &&
          name == other.name &&
          host == other.host &&
          username == other.username &&
          port == other.port &&
          authMethod == other.authMethod &&
          folder == other.folder &&
          description == other.description &&
          tags == other.tags &&
          password == other.password &&
          privateKeyPath == other.privateKeyPath &&
          passphrase == other.passphrase;
}
