// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_alive`, `state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `McpState`

/// MCP 端点常量(`http://127.0.0.1:9123/mcp`)。
String mcpEndpoint() => RustLib.instance.api.crateApiMcpMcpEndpoint();

/// MCP 监听端口(9123)。
int mcpPort() => RustLib.instance.api.crateApiMcpMcpPort();

/// 读取当前 MCP 服务状态(同步,面板可随时轮询)。
McpStatusDto mcpStatus() => RustLib.instance.api.crateApiMcpMcpStatus();

/// 启动本机 MCP 服务(幂等:已运行则直接返回成功)。
///
/// spawn 后等待 250ms;若任务已结束说明 `start_mcp_server` 绑定失败(多为端口被占),返回错误。
Future<void> mcpStart() => RustLib.instance.api.crateApiMcpMcpStart();

/// 停止本机 MCP 服务(幂等:未运行则无操作)。abort spawn 的任务以释放监听端口。
Future<void> mcpStop() => RustLib.instance.api.crateApiMcpMcpStop();

/// 列出 MCP 暴露的工具(静态清单,镜像 core `RShellMcpServer`)。
List<McpToolDto> mcpTools() => RustLib.instance.api.crateApiMcpMcpTools();

/// MCP 服务状态快照(面板状态卡用)。
class McpStatusDto {
  final bool running;
  final String host;
  final int port;
  final String endpoint;

  /// 运行时长(秒);未运行为 0。
  final BigInt uptimeSecs;

  /// 暴露的工具数量。
  final int toolCount;

  const McpStatusDto({
    required this.running,
    required this.host,
    required this.port,
    required this.endpoint,
    required this.uptimeSecs,
    required this.toolCount,
  });

  @override
  int get hashCode =>
      running.hashCode ^
      host.hashCode ^
      port.hashCode ^
      endpoint.hashCode ^
      uptimeSecs.hashCode ^
      toolCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is McpStatusDto &&
          runtimeType == other.runtimeType &&
          running == other.running &&
          host == other.host &&
          port == other.port &&
          endpoint == other.endpoint &&
          uptimeSecs == other.uptimeSecs &&
          toolCount == other.toolCount;
}

/// 一个 MCP 工具的展示信息。
class McpToolDto {
  final String name;
  final String summary;

  /// 分类(决定面板图标):`session` / `exec` / `file` / `dir` / `connection`。
  final String category;

  const McpToolDto({
    required this.name,
    required this.summary,
    required this.category,
  });

  @override
  int get hashCode => name.hashCode ^ summary.hashCode ^ category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is McpToolDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          summary == other.summary &&
          category == other.category;
}
