// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect`, `error`, `sample`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

/// 周期性推送某连接的实时系统指标(Dart 得到 `Stream<StatsFrame>`)。
///
/// - `interval_ms`:相邻两次采样的间隔(下限 250ms 防过载,远端命令本身也有耗时)。
/// - 首个成功帧的 CPU%/网速为 0(需两帧差分),内存 / 磁盘 / 负载 / uptime / OS 立即可用。
/// - 采集失败 → 推带 `error` 的帧并在 `interval` 后自重试(主机恢复即自动回到 `sample`)。
/// - Dart 取消订阅 → `sink.add` 失败 → 循环退出。**永不返回 `Err`**(避免 frb unawaited 未捕获)。
/// - 复用共享会话,**不主动关闭**(终端 / SFTP 可能在用;由终端「最后标签关闭」统一回收)。
Stream<StatsFrame> statsStream({
  required String connectionId,
  required int intervalMs,
}) => RustLib.instance.api.crateApiMonitorStatsStream(
  connectionId: connectionId,
  intervalMs: intervalMs,
);

/// 周期性推送**本机**(运行 GUI 的这台电脑)的实时系统指标(Dart 得到 `Stream<StatsFrame>`)。
///
/// 与 [`stats_stream`] 同范式,但数据来自本机 `sysinfo`(见 [`r_shell_core::local`]),
/// **无需任何连接 / 会话**:本机采集几乎不会失败,故恒推 `sample` 帧。`LocalCollector`
/// 跨循环复用(CPU% 依赖两次刷新间的增量),首帧 CPU%/网速为 0(需两帧差分)。
Stream<StatsFrame> localStatsStream({required int intervalMs}) => RustLib
    .instance
    .api
    .crateApiMonitorLocalStatsStream(intervalMs: intervalMs);

/// 单个磁盘 / 卷的用量(KB 为千字节,`percent` 为 0.0..=100.0)。
/// `mount` 是人类可读标签:Unix 挂载点(`/`、`/data`)或 Windows 盘符(`C:`)。
class DiskUsageDto {
  final String mount;
  final PlatformInt64 usedKb;
  final PlatformInt64 totalKb;
  final double percent;

  const DiskUsageDto({
    required this.mount,
    required this.usedKb,
    required this.totalKb,
    required this.percent,
  });

  @override
  int get hashCode =>
      mount.hashCode ^ usedKb.hashCode ^ totalKb.hashCode ^ percent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiskUsageDto &&
          runtimeType == other.runtimeType &&
          mount == other.mount &&
          usedKb == other.usedKb &&
          totalKb == other.totalKb &&
          percent == other.percent;
}

/// 监控流的一帧:`sample` 与 `error` 互斥——成功时 `sample=Some`、`error=None`;
/// 失败时 `sample=None`、`error=Some(原因)`。错误走数据帧而非 frb 的 `Err`(见模块
/// 文档),Dart 端在 `onData` 内按字段分支处理。
class StatsFrame {
  final SystemStatsDto? sample;
  final String? error;

  const StatsFrame({this.sample, this.error});

  @override
  int get hashCode => sample.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsFrame &&
          runtimeType == other.runtimeType &&
          sample == other.sample &&
          error == other.error;
}

/// 一帧派生后的系统指标(百分比 0.0..=100.0,KB 为千字节,速率为字节/秒)。
/// 与 core [`SystemStats`] 一一映射,仅做 frb 友好的类型收敛。
class SystemStatsDto {
  final double cpuPercent;
  final double memPercent;
  final PlatformInt64 memUsedKb;
  final PlatformInt64 memTotalKb;
  final double swapPercent;
  final PlatformInt64 swapUsedKb;
  final PlatformInt64 swapTotalKb;

  /// 主盘(最大的真实文件系统):百分比 / 已用 / 总量。
  final double diskPercent;
  final PlatformInt64 diskUsedKb;
  final PlatformInt64 diskTotalKb;

  /// 全部真实磁盘 / 卷(按容量从大到小),用于多盘视图。
  final List<DiskUsageDto> disks;

  /// 字节/秒。
  final double netRxPerSec;
  final double netTxPerSec;
  final double load1;
  final double uptimeSecs;
  final int cpuCores;
  final String os;

  const SystemStatsDto({
    required this.cpuPercent,
    required this.memPercent,
    required this.memUsedKb,
    required this.memTotalKb,
    required this.swapPercent,
    required this.swapUsedKb,
    required this.swapTotalKb,
    required this.diskPercent,
    required this.diskUsedKb,
    required this.diskTotalKb,
    required this.disks,
    required this.netRxPerSec,
    required this.netTxPerSec,
    required this.load1,
    required this.uptimeSecs,
    required this.cpuCores,
    required this.os,
  });

  @override
  int get hashCode =>
      cpuPercent.hashCode ^
      memPercent.hashCode ^
      memUsedKb.hashCode ^
      memTotalKb.hashCode ^
      swapPercent.hashCode ^
      swapUsedKb.hashCode ^
      swapTotalKb.hashCode ^
      diskPercent.hashCode ^
      diskUsedKb.hashCode ^
      diskTotalKb.hashCode ^
      disks.hashCode ^
      netRxPerSec.hashCode ^
      netTxPerSec.hashCode ^
      load1.hashCode ^
      uptimeSecs.hashCode ^
      cpuCores.hashCode ^
      os.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemStatsDto &&
          runtimeType == other.runtimeType &&
          cpuPercent == other.cpuPercent &&
          memPercent == other.memPercent &&
          memUsedKb == other.memUsedKb &&
          memTotalKb == other.memTotalKb &&
          swapPercent == other.swapPercent &&
          swapUsedKb == other.swapUsedKb &&
          swapTotalKb == other.swapTotalKb &&
          diskPercent == other.diskPercent &&
          diskUsedKb == other.diskUsedKb &&
          diskTotalKb == other.diskTotalKb &&
          disks == other.disks &&
          netRxPerSec == other.netRxPerSec &&
          netTxPerSec == other.netTxPerSec &&
          load1 == other.load1 &&
          uptimeSecs == other.uptimeSecs &&
          cpuCores == other.cpuCores &&
          os == other.os;
}
