// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// 列出某连接的远程目录(结构化,跨平台)。
Future<List<SftpEntryDto>> sftpList({
  required String connectionId,
  required String path,
}) => RustLib.instance.api.crateApiSftpSftpList(
  connectionId: connectionId,
  path: path,
);

/// 取远程默认目录(home)的绝对路径(`realpath(".")`)。
Future<String> sftpHome({required String connectionId}) =>
    RustLib.instance.api.crateApiSftpSftpHome(connectionId: connectionId);

/// 把远程路径规范化为绝对形式(用于「返回上级」解析 `..`)。
Future<String> sftpRealpath({
  required String connectionId,
  required String path,
}) => RustLib.instance.api.crateApiSftpSftpRealpath(
  connectionId: connectionId,
  path: path,
);

/// 递归删除远程文件 / 目录。
Future<void> sftpDelete({required String connectionId, required String path}) =>
    RustLib.instance.api.crateApiSftpSftpDelete(
      connectionId: connectionId,
      path: path,
    );

/// 重命名 / 移动远程路径(`from` → `to`,均为绝对路径)。
Future<void> sftpRename({
  required String connectionId,
  required String from,
  required String to,
}) => RustLib.instance.api.crateApiSftpSftpRename(
  connectionId: connectionId,
  from: from,
  to: to,
);

/// 读取远程文件全部字节(用于「打开编辑」)。注意大文件会整体进内存。
Future<Uint8List> sftpReadFile({
  required String connectionId,
  required String path,
}) => RustLib.instance.api.crateApiSftpSftpReadFile(
  connectionId: connectionId,
  path: path,
);

/// 把字节写回远程文件(用于「编辑后保存」,创建 / 覆盖)。
Future<void> sftpWriteFile({
  required String connectionId,
  required String path,
  required List<int> data,
}) => RustLib.instance.api.crateApiSftpSftpWriteFile(
  connectionId: connectionId,
  path: path,
  data: data,
);

/// 上传本地文件到远程。进度经 `sink` 推送(Dart 得到 `Stream<TransferProgress>`)。
/// 进度在此节流(≥128KB 或完成才推一帧),避免大文件刷爆 stream。
Stream<TransferProgress> sftpUpload({
  required String connectionId,
  required String localPath,
  required String remotePath,
}) => RustLib.instance.api.crateApiSftpSftpUpload(
  connectionId: connectionId,
  localPath: localPath,
  remotePath: remotePath,
);

/// 下载远程文件到本地。进度经 `sink` 推送(同上,带节流)。
Stream<TransferProgress> sftpDownload({
  required String connectionId,
  required String remotePath,
  required String localPath,
}) => RustLib.instance.api.crateApiSftpSftpDownload(
  connectionId: connectionId,
  remotePath: remotePath,
  localPath: localPath,
);

/// 单条远程文件 / 目录(脱敏:仅元数据,无内容)。
class SftpEntryDto {
  final String name;

  /// "dir" | "file" | "symlink"
  final String kind;

  /// 字节大小(目录 / 未知为 0)。
  final PlatformInt64 size;

  /// Unix 权限串,如 `rwxr-xr-x`(未知为空)。
  final String permissions;

  /// 修改时间(Unix 秒;服务器未给为 0)。Dart 侧格式化。
  final PlatformInt64 modifiedUnix;

  const SftpEntryDto({
    required this.name,
    required this.kind,
    required this.size,
    required this.permissions,
    required this.modifiedUnix,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      kind.hashCode ^
      size.hashCode ^
      permissions.hashCode ^
      modifiedUnix.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpEntryDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          kind == other.kind &&
          size == other.size &&
          permissions == other.permissions &&
          modifiedUnix == other.modifiedUnix;
}

/// 一帧传输进度。完成由 stream 自然结束(onDone)、失败由 stream 错误(onError)表达。
class TransferProgress {
  final PlatformInt64 transferred;
  final PlatformInt64 total;

  const TransferProgress({required this.transferred, required this.total});

  @override
  int get hashCode => transferred.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferProgress &&
          runtimeType == other.runtimeType &&
          transferred == other.transferred &&
          total == other.total;
}
