// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 确保某个已保存连接有一个活跃 SSH 会话(幂等:已连接则复用,供同主机多标签共用)。
Future<void> sessionOpen({required String connectionId}) => RustLib.instance.api
    .crateApiTerminalSessionOpen(connectionId: connectionId);

/// 关闭某连接的 SSH 会话(同时清理其名下所有 PTY)。
Future<void> sessionClose({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiTerminalSessionClose(connectionId: connectionId);

/// 该连接当前是否有活跃会话。
Future<bool> sessionIsOpen({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiTerminalSessionIsOpen(connectionId: connectionId);

/// 在已打开的会话上新开一个 PTY,返回唯一 `pty_id`(用于后续 write / resize / close)。
Future<String> ptyOpen({
  required String connectionId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiTerminalPtyOpen(
  connectionId: connectionId,
  cols: cols,
  rows: rows,
);

/// 订阅某 PTY 的输出字节流(Dart 侧得到 `Stream<Uint8List>`)。PTY 关闭即流自然结束。
Stream<Uint8List> ptySubscribe({required String ptyId}) =>
    RustLib.instance.api.crateApiTerminalPtySubscribe(ptyId: ptyId);

/// 向 PTY 写入输入字节(键盘)。
Future<void> ptyWrite({required String ptyId, required List<int> data}) =>
    RustLib.instance.api.crateApiTerminalPtyWrite(ptyId: ptyId, data: data);

/// 调整 PTY 窗口尺寸(列 / 行)。
Future<void> ptyResize({
  required String ptyId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiTerminalPtyResize(
  ptyId: ptyId,
  cols: cols,
  rows: rows,
);

/// 关闭 PTY(终端标签关闭时调用)。
Future<void> ptyClose({required String ptyId}) =>
    RustLib.instance.api.crateApiTerminalPtyClose(ptyId: ptyId);
