// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/adb.dart';
import 'api/blockterm.dart';
import 'api/connections.dart';
import 'api/mcp.dart';
import 'api/monitor.dart';
import 'api/sftp.dart';
import 'api/simple.dart';
import 'api/terminal.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 2037462083;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_r_shell_desktop',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiAdbAdbConnect({required String hostPort});

  Future<String> crateApiAdbAdbPair({
    required String hostPort,
    required String code,
  });

  Future<BlockResultDto> crateApiBlocktermBlockRunLocal({
    required String command,
    required String cwd,
  });

  Future<BlockResultDto> crateApiBlocktermBlockRunRemote({
    required String connectionId,
    required String command,
    required String cwd,
  });

  ConnectionDto crateApiConnectionsCreateConnection({
    required ConnectionInput input,
  });

  void crateApiConnectionsDeleteConnection({required String id});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  List<ConnectionDto> crateApiConnectionsListConnections();

  Stream<StatsFrame> crateApiMonitorLocalStatsStream({required int intervalMs});

  String crateApiMcpMcpEndpoint();

  int crateApiMcpMcpPort();

  Future<void> crateApiMcpMcpStart();

  McpStatusDto crateApiMcpMcpStatus();

  Future<void> crateApiMcpMcpStop();

  List<McpToolDto> crateApiMcpMcpTools();

  Future<void> crateApiTerminalPtyClose({required String ptyId});

  Future<String> crateApiTerminalPtyOpen({
    required String connectionId,
    required int cols,
    required int rows,
  });

  Future<void> crateApiTerminalPtyResize({
    required String ptyId,
    required int cols,
    required int rows,
  });

  Stream<Uint8List> crateApiTerminalPtySubscribe({required String ptyId});

  Future<void> crateApiTerminalPtyWrite({
    required String ptyId,
    required List<int> data,
  });

  Future<void> crateApiTerminalSessionClose({required String connectionId});

  Future<bool> crateApiTerminalSessionIsOpen({required String connectionId});

  Future<void> crateApiTerminalSessionOpen({required String connectionId});

  Future<void> crateApiSftpSftpDelete({
    required String connectionId,
    required String path,
  });

  Stream<TransferProgress> crateApiSftpSftpDownload({
    required String connectionId,
    required String remotePath,
    required String localPath,
  });

  Future<String> crateApiSftpSftpHome({required String connectionId});

  Future<List<SftpEntryDto>> crateApiSftpSftpList({
    required String connectionId,
    required String path,
  });

  Future<Uint8List> crateApiSftpSftpReadFile({
    required String connectionId,
    required String path,
  });

  Future<String> crateApiSftpSftpRealpath({
    required String connectionId,
    required String path,
  });

  Future<void> crateApiSftpSftpRename({
    required String connectionId,
    required String from,
    required String to,
  });

  Stream<TransferProgress> crateApiSftpSftpUpload({
    required String connectionId,
    required String localPath,
    required String remotePath,
  });

  Future<void> crateApiSftpSftpWriteFile({
    required String connectionId,
    required String path,
    required List<int> data,
  });

  Stream<StatsFrame> crateApiMonitorStatsStream({
    required String connectionId,
    required int intervalMs,
  });

  ConnectionDto crateApiConnectionsUpdateConnection({
    required String id,
    required ConnectionInput input,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiAdbAdbConnect({required String hostPort}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostPort, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAdbAdbConnectConstMeta,
        argValues: [hostPort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAdbAdbConnectConstMeta =>
      const TaskConstMeta(debugName: "adb_connect", argNames: ["hostPort"]);

  @override
  Future<String> crateApiAdbAdbPair({
    required String hostPort,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hostPort, serializer);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAdbAdbPairConstMeta,
        argValues: [hostPort, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAdbAdbPairConstMeta => const TaskConstMeta(
    debugName: "adb_pair",
    argNames: ["hostPort", "code"],
  );

  @override
  Future<BlockResultDto> crateApiBlocktermBlockRunLocal({
    required String command,
    required String cwd,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(command, serializer);
          sse_encode_String(cwd, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_block_result_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBlocktermBlockRunLocalConstMeta,
        argValues: [command, cwd],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBlocktermBlockRunLocalConstMeta =>
      const TaskConstMeta(
        debugName: "block_run_local",
        argNames: ["command", "cwd"],
      );

  @override
  Future<BlockResultDto> crateApiBlocktermBlockRunRemote({
    required String connectionId,
    required String command,
    required String cwd,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          sse_encode_String(command, serializer);
          sse_encode_String(cwd, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_block_result_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBlocktermBlockRunRemoteConstMeta,
        argValues: [connectionId, command, cwd],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBlocktermBlockRunRemoteConstMeta =>
      const TaskConstMeta(
        debugName: "block_run_remote",
        argNames: ["connectionId", "command", "cwd"],
      );

  @override
  ConnectionDto crateApiConnectionsCreateConnection({
    required ConnectionInput input,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_connection_input(input, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectionsCreateConnectionConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionsCreateConnectionConstMeta =>
      const TaskConstMeta(debugName: "create_connection", argNames: ["input"]);

  @override
  void crateApiConnectionsDeleteConnection({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectionsDeleteConnectionConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionsDeleteConnectionConstMeta =>
      const TaskConstMeta(debugName: "delete_connection", argNames: ["id"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  List<ConnectionDto> crateApiConnectionsListConnections() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_connection_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionsListConnectionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionsListConnectionsConstMeta =>
      const TaskConstMeta(debugName: "list_connections", argNames: []);

  @override
  Stream<StatsFrame> crateApiMonitorLocalStatsStream({
    required int intervalMs,
  }) {
    final sink = RustStreamSink<StatsFrame>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_u_32(intervalMs, serializer);
            sse_encode_StreamSink_stats_frame_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiMonitorLocalStatsStreamConstMeta,
          argValues: [intervalMs, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMonitorLocalStatsStreamConstMeta =>
      const TaskConstMeta(
        debugName: "local_stats_stream",
        argNames: ["intervalMs", "sink"],
      );

  @override
  String crateApiMcpMcpEndpoint() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMcpMcpEndpointConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpMcpEndpointConstMeta =>
      const TaskConstMeta(debugName: "mcp_endpoint", argNames: []);

  @override
  int crateApiMcpMcpPort() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMcpMcpPortConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpMcpPortConstMeta =>
      const TaskConstMeta(debugName: "mcp_port", argNames: []);

  @override
  Future<void> crateApiMcpMcpStart() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpMcpStartConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpMcpStartConstMeta =>
      const TaskConstMeta(debugName: "mcp_start", argNames: []);

  @override
  McpStatusDto crateApiMcpMcpStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mcp_status_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMcpMcpStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpMcpStatusConstMeta =>
      const TaskConstMeta(debugName: "mcp_status", argNames: []);

  @override
  Future<void> crateApiMcpMcpStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMcpMcpStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpMcpStopConstMeta =>
      const TaskConstMeta(debugName: "mcp_stop", argNames: []);

  @override
  List<McpToolDto> crateApiMcpMcpTools() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mcp_tool_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMcpMcpToolsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMcpMcpToolsConstMeta =>
      const TaskConstMeta(debugName: "mcp_tools", argNames: []);

  @override
  Future<void> crateApiTerminalPtyClose({required String ptyId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ptyId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTerminalPtyCloseConstMeta,
        argValues: [ptyId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalPtyCloseConstMeta =>
      const TaskConstMeta(debugName: "pty_close", argNames: ["ptyId"]);

  @override
  Future<String> crateApiTerminalPtyOpen({
    required String connectionId,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          sse_encode_u_16(cols, serializer);
          sse_encode_u_16(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTerminalPtyOpenConstMeta,
        argValues: [connectionId, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalPtyOpenConstMeta => const TaskConstMeta(
    debugName: "pty_open",
    argNames: ["connectionId", "cols", "rows"],
  );

  @override
  Future<void> crateApiTerminalPtyResize({
    required String ptyId,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ptyId, serializer);
          sse_encode_u_16(cols, serializer);
          sse_encode_u_16(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTerminalPtyResizeConstMeta,
        argValues: [ptyId, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalPtyResizeConstMeta => const TaskConstMeta(
    debugName: "pty_resize",
    argNames: ["ptyId", "cols", "rows"],
  );

  @override
  Stream<Uint8List> crateApiTerminalPtySubscribe({required String ptyId}) {
    final sink = RustStreamSink<Uint8List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(ptyId, serializer);
            sse_encode_StreamSink_list_prim_u_8_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 20,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiTerminalPtySubscribeConstMeta,
          argValues: [ptyId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTerminalPtySubscribeConstMeta =>
      const TaskConstMeta(
        debugName: "pty_subscribe",
        argNames: ["ptyId", "sink"],
      );

  @override
  Future<void> crateApiTerminalPtyWrite({
    required String ptyId,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ptyId, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTerminalPtyWriteConstMeta,
        argValues: [ptyId, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalPtyWriteConstMeta =>
      const TaskConstMeta(debugName: "pty_write", argNames: ["ptyId", "data"]);

  @override
  Future<void> crateApiTerminalSessionClose({required String connectionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTerminalSessionCloseConstMeta,
        argValues: [connectionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalSessionCloseConstMeta =>
      const TaskConstMeta(
        debugName: "session_close",
        argNames: ["connectionId"],
      );

  @override
  Future<bool> crateApiTerminalSessionIsOpen({required String connectionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalSessionIsOpenConstMeta,
        argValues: [connectionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalSessionIsOpenConstMeta =>
      const TaskConstMeta(
        debugName: "session_is_open",
        argNames: ["connectionId"],
      );

  @override
  Future<void> crateApiTerminalSessionOpen({required String connectionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTerminalSessionOpenConstMeta,
        argValues: [connectionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalSessionOpenConstMeta =>
      const TaskConstMeta(
        debugName: "session_open",
        argNames: ["connectionId"],
      );

  @override
  Future<void> crateApiSftpSftpDelete({
    required String connectionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpDeleteConstMeta,
        argValues: [connectionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpDeleteConstMeta => const TaskConstMeta(
    debugName: "sftp_delete",
    argNames: ["connectionId", "path"],
  );

  @override
  Stream<TransferProgress> crateApiSftpSftpDownload({
    required String connectionId,
    required String remotePath,
    required String localPath,
  }) {
    final sink = RustStreamSink<TransferProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(connectionId, serializer);
            sse_encode_String(remotePath, serializer);
            sse_encode_String(localPath, serializer);
            sse_encode_StreamSink_transfer_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 26,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiSftpSftpDownloadConstMeta,
          argValues: [connectionId, remotePath, localPath, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSftpSftpDownloadConstMeta => const TaskConstMeta(
    debugName: "sftp_download",
    argNames: ["connectionId", "remotePath", "localPath", "sink"],
  );

  @override
  Future<String> crateApiSftpSftpHome({required String connectionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpHomeConstMeta,
        argValues: [connectionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpHomeConstMeta =>
      const TaskConstMeta(debugName: "sftp_home", argNames: ["connectionId"]);

  @override
  Future<List<SftpEntryDto>> crateApiSftpSftpList({
    required String connectionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_sftp_entry_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpListConstMeta,
        argValues: [connectionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpListConstMeta => const TaskConstMeta(
    debugName: "sftp_list",
    argNames: ["connectionId", "path"],
  );

  @override
  Future<Uint8List> crateApiSftpSftpReadFile({
    required String connectionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpReadFileConstMeta,
        argValues: [connectionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpReadFileConstMeta => const TaskConstMeta(
    debugName: "sftp_read_file",
    argNames: ["connectionId", "path"],
  );

  @override
  Future<String> crateApiSftpSftpRealpath({
    required String connectionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpRealpathConstMeta,
        argValues: [connectionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpRealpathConstMeta => const TaskConstMeta(
    debugName: "sftp_realpath",
    argNames: ["connectionId", "path"],
  );

  @override
  Future<void> crateApiSftpSftpRename({
    required String connectionId,
    required String from,
    required String to,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          sse_encode_String(from, serializer);
          sse_encode_String(to, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpRenameConstMeta,
        argValues: [connectionId, from, to],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpRenameConstMeta => const TaskConstMeta(
    debugName: "sftp_rename",
    argNames: ["connectionId", "from", "to"],
  );

  @override
  Stream<TransferProgress> crateApiSftpSftpUpload({
    required String connectionId,
    required String localPath,
    required String remotePath,
  }) {
    final sink = RustStreamSink<TransferProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(connectionId, serializer);
            sse_encode_String(localPath, serializer);
            sse_encode_String(remotePath, serializer);
            sse_encode_StreamSink_transfer_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 32,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiSftpSftpUploadConstMeta,
          argValues: [connectionId, localPath, remotePath, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSftpSftpUploadConstMeta => const TaskConstMeta(
    debugName: "sftp_upload",
    argNames: ["connectionId", "localPath", "remotePath", "sink"],
  );

  @override
  Future<void> crateApiSftpSftpWriteFile({
    required String connectionId,
    required String path,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          sse_encode_String(path, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpWriteFileConstMeta,
        argValues: [connectionId, path, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpWriteFileConstMeta => const TaskConstMeta(
    debugName: "sftp_write_file",
    argNames: ["connectionId", "path", "data"],
  );

  @override
  Stream<StatsFrame> crateApiMonitorStatsStream({
    required String connectionId,
    required int intervalMs,
  }) {
    final sink = RustStreamSink<StatsFrame>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(connectionId, serializer);
            sse_encode_u_32(intervalMs, serializer);
            sse_encode_StreamSink_stats_frame_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 34,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiMonitorStatsStreamConstMeta,
          argValues: [connectionId, intervalMs, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMonitorStatsStreamConstMeta => const TaskConstMeta(
    debugName: "stats_stream",
    argNames: ["connectionId", "intervalMs", "sink"],
  );

  @override
  ConnectionDto crateApiConnectionsUpdateConnection({
    required String id,
    required ConnectionInput input,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_box_autoadd_connection_input(input, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectionsUpdateConnectionConstMeta,
        argValues: [id, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionsUpdateConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "update_connection",
        argNames: ["id", "input"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<StatsFrame> dco_decode_StreamSink_stats_frame_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<TransferProgress> dco_decode_StreamSink_transfer_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BlockResultDto dco_decode_block_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BlockResultDto(
      body: dco_decode_String(arr[0]),
      exitCode: dco_decode_i_32(arr[1]),
      cwd: dco_decode_String(arr[2]),
      hadMarker: dco_decode_bool(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ConnectionInput dco_decode_box_autoadd_connection_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_connection_input(raw);
  }

  @protected
  SystemStatsDto dco_decode_box_autoadd_system_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_system_stats_dto(raw);
  }

  @protected
  ConnectionDto dco_decode_connection_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return ConnectionDto(
      id: dco_decode_String(arr[0]),
      protocol: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      host: dco_decode_String(arr[3]),
      port: dco_decode_u_16(arr[4]),
      username: dco_decode_String(arr[5]),
      folder: dco_decode_String(arr[6]),
      description: dco_decode_String(arr[7]),
      authMethod: dco_decode_String(arr[8]),
      status: dco_decode_String(arr[9]),
      tags: dco_decode_list_String(arr[10]),
      hasPassword: dco_decode_bool(arr[11]),
      hasPrivateKeyPath: dco_decode_bool(arr[12]),
      hasPassphrase: dco_decode_bool(arr[13]),
    );
  }

  @protected
  ConnectionInput dco_decode_connection_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return ConnectionInput(
      protocol: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      host: dco_decode_String(arr[2]),
      username: dco_decode_String(arr[3]),
      port: dco_decode_u_16(arr[4]),
      authMethod: dco_decode_String(arr[5]),
      folder: dco_decode_String(arr[6]),
      description: dco_decode_String(arr[7]),
      tags: dco_decode_list_String(arr[8]),
      password: dco_decode_opt_String(arr[9]),
      privateKeyPath: dco_decode_opt_String(arr[10]),
      passphrase: dco_decode_opt_String(arr[11]),
    );
  }

  @protected
  DiskUsageDto dco_decode_disk_usage_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DiskUsageDto(
      mount: dco_decode_String(arr[0]),
      usedKb: dco_decode_i_64(arr[1]),
      totalKb: dco_decode_i_64(arr[2]),
      percent: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConnectionDto> dco_decode_list_connection_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_connection_dto).toList();
  }

  @protected
  List<DiskUsageDto> dco_decode_list_disk_usage_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_disk_usage_dto).toList();
  }

  @protected
  List<McpToolDto> dco_decode_list_mcp_tool_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mcp_tool_dto).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SftpEntryDto> dco_decode_list_sftp_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sftp_entry_dto).toList();
  }

  @protected
  McpStatusDto dco_decode_mcp_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return McpStatusDto(
      running: dco_decode_bool(arr[0]),
      host: dco_decode_String(arr[1]),
      port: dco_decode_u_16(arr[2]),
      endpoint: dco_decode_String(arr[3]),
      uptimeSecs: dco_decode_u_64(arr[4]),
      toolCount: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  McpToolDto dco_decode_mcp_tool_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return McpToolDto(
      name: dco_decode_String(arr[0]),
      summary: dco_decode_String(arr[1]),
      category: dco_decode_String(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SystemStatsDto? dco_decode_opt_box_autoadd_system_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_system_stats_dto(raw);
  }

  @protected
  SftpEntryDto dco_decode_sftp_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SftpEntryDto(
      name: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      size: dco_decode_i_64(arr[2]),
      permissions: dco_decode_String(arr[3]),
      modifiedUnix: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  StatsFrame dco_decode_stats_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StatsFrame(
      sample: dco_decode_opt_box_autoadd_system_stats_dto(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  SystemStatsDto dco_decode_system_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return SystemStatsDto(
      cpuPercent: dco_decode_f_64(arr[0]),
      memPercent: dco_decode_f_64(arr[1]),
      memUsedKb: dco_decode_i_64(arr[2]),
      memTotalKb: dco_decode_i_64(arr[3]),
      swapPercent: dco_decode_f_64(arr[4]),
      swapUsedKb: dco_decode_i_64(arr[5]),
      swapTotalKb: dco_decode_i_64(arr[6]),
      diskPercent: dco_decode_f_64(arr[7]),
      diskUsedKb: dco_decode_i_64(arr[8]),
      diskTotalKb: dco_decode_i_64(arr[9]),
      disks: dco_decode_list_disk_usage_dto(arr[10]),
      netRxPerSec: dco_decode_f_64(arr[11]),
      netTxPerSec: dco_decode_f_64(arr[12]),
      load1: dco_decode_f_64(arr[13]),
      uptimeSecs: dco_decode_f_64(arr[14]),
      cpuCores: dco_decode_u_32(arr[15]),
      os: dco_decode_String(arr[16]),
    );
  }

  @protected
  TransferProgress dco_decode_transfer_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TransferProgress(
      transferred: dco_decode_i_64(arr[0]),
      total: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<StatsFrame> sse_decode_StreamSink_stats_frame_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<TransferProgress> sse_decode_StreamSink_transfer_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BlockResultDto sse_decode_block_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_body = sse_decode_String(deserializer);
    var var_exitCode = sse_decode_i_32(deserializer);
    var var_cwd = sse_decode_String(deserializer);
    var var_hadMarker = sse_decode_bool(deserializer);
    return BlockResultDto(
      body: var_body,
      exitCode: var_exitCode,
      cwd: var_cwd,
      hadMarker: var_hadMarker,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ConnectionInput sse_decode_box_autoadd_connection_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_connection_input(deserializer));
  }

  @protected
  SystemStatsDto sse_decode_box_autoadd_system_stats_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_system_stats_dto(deserializer));
  }

  @protected
  ConnectionDto sse_decode_connection_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_protocol = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_folder = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_authMethod = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_hasPassword = sse_decode_bool(deserializer);
    var var_hasPrivateKeyPath = sse_decode_bool(deserializer);
    var var_hasPassphrase = sse_decode_bool(deserializer);
    return ConnectionDto(
      id: var_id,
      protocol: var_protocol,
      name: var_name,
      host: var_host,
      port: var_port,
      username: var_username,
      folder: var_folder,
      description: var_description,
      authMethod: var_authMethod,
      status: var_status,
      tags: var_tags,
      hasPassword: var_hasPassword,
      hasPrivateKeyPath: var_hasPrivateKeyPath,
      hasPassphrase: var_hasPassphrase,
    );
  }

  @protected
  ConnectionInput sse_decode_connection_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_protocol = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_authMethod = sse_decode_String(deserializer);
    var var_folder = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_password = sse_decode_opt_String(deserializer);
    var var_privateKeyPath = sse_decode_opt_String(deserializer);
    var var_passphrase = sse_decode_opt_String(deserializer);
    return ConnectionInput(
      protocol: var_protocol,
      name: var_name,
      host: var_host,
      username: var_username,
      port: var_port,
      authMethod: var_authMethod,
      folder: var_folder,
      description: var_description,
      tags: var_tags,
      password: var_password,
      privateKeyPath: var_privateKeyPath,
      passphrase: var_passphrase,
    );
  }

  @protected
  DiskUsageDto sse_decode_disk_usage_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mount = sse_decode_String(deserializer);
    var var_usedKb = sse_decode_i_64(deserializer);
    var var_totalKb = sse_decode_i_64(deserializer);
    var var_percent = sse_decode_f_64(deserializer);
    return DiskUsageDto(
      mount: var_mount,
      usedKb: var_usedKb,
      totalKb: var_totalKb,
      percent: var_percent,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConnectionDto> sse_decode_list_connection_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConnectionDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_connection_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<DiskUsageDto> sse_decode_list_disk_usage_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DiskUsageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_disk_usage_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<McpToolDto> sse_decode_list_mcp_tool_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <McpToolDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mcp_tool_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SftpEntryDto> sse_decode_list_sftp_entry_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SftpEntryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sftp_entry_dto(deserializer));
    }
    return ans_;
  }

  @protected
  McpStatusDto sse_decode_mcp_status_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_running = sse_decode_bool(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_endpoint = sse_decode_String(deserializer);
    var var_uptimeSecs = sse_decode_u_64(deserializer);
    var var_toolCount = sse_decode_u_32(deserializer);
    return McpStatusDto(
      running: var_running,
      host: var_host,
      port: var_port,
      endpoint: var_endpoint,
      uptimeSecs: var_uptimeSecs,
      toolCount: var_toolCount,
    );
  }

  @protected
  McpToolDto sse_decode_mcp_tool_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    return McpToolDto(
      name: var_name,
      summary: var_summary,
      category: var_category,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SystemStatsDto? sse_decode_opt_box_autoadd_system_stats_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_system_stats_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SftpEntryDto sse_decode_sftp_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_size = sse_decode_i_64(deserializer);
    var var_permissions = sse_decode_String(deserializer);
    var var_modifiedUnix = sse_decode_i_64(deserializer);
    return SftpEntryDto(
      name: var_name,
      kind: var_kind,
      size: var_size,
      permissions: var_permissions,
      modifiedUnix: var_modifiedUnix,
    );
  }

  @protected
  StatsFrame sse_decode_stats_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sample = sse_decode_opt_box_autoadd_system_stats_dto(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return StatsFrame(sample: var_sample, error: var_error);
  }

  @protected
  SystemStatsDto sse_decode_system_stats_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cpuPercent = sse_decode_f_64(deserializer);
    var var_memPercent = sse_decode_f_64(deserializer);
    var var_memUsedKb = sse_decode_i_64(deserializer);
    var var_memTotalKb = sse_decode_i_64(deserializer);
    var var_swapPercent = sse_decode_f_64(deserializer);
    var var_swapUsedKb = sse_decode_i_64(deserializer);
    var var_swapTotalKb = sse_decode_i_64(deserializer);
    var var_diskPercent = sse_decode_f_64(deserializer);
    var var_diskUsedKb = sse_decode_i_64(deserializer);
    var var_diskTotalKb = sse_decode_i_64(deserializer);
    var var_disks = sse_decode_list_disk_usage_dto(deserializer);
    var var_netRxPerSec = sse_decode_f_64(deserializer);
    var var_netTxPerSec = sse_decode_f_64(deserializer);
    var var_load1 = sse_decode_f_64(deserializer);
    var var_uptimeSecs = sse_decode_f_64(deserializer);
    var var_cpuCores = sse_decode_u_32(deserializer);
    var var_os = sse_decode_String(deserializer);
    return SystemStatsDto(
      cpuPercent: var_cpuPercent,
      memPercent: var_memPercent,
      memUsedKb: var_memUsedKb,
      memTotalKb: var_memTotalKb,
      swapPercent: var_swapPercent,
      swapUsedKb: var_swapUsedKb,
      swapTotalKb: var_swapTotalKb,
      diskPercent: var_diskPercent,
      diskUsedKb: var_diskUsedKb,
      diskTotalKb: var_diskTotalKb,
      disks: var_disks,
      netRxPerSec: var_netRxPerSec,
      netTxPerSec: var_netTxPerSec,
      load1: var_load1,
      uptimeSecs: var_uptimeSecs,
      cpuCores: var_cpuCores,
      os: var_os,
    );
  }

  @protected
  TransferProgress sse_decode_transfer_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transferred = sse_decode_i_64(deserializer);
    var var_total = sse_decode_i_64(deserializer);
    return TransferProgress(transferred: var_transferred, total: var_total);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_stats_frame_Sse(
    RustStreamSink<StatsFrame> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_stats_frame,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_transfer_progress_Sse(
    RustStreamSink<TransferProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_transfer_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_block_result_dto(
    BlockResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.body, serializer);
    sse_encode_i_32(self.exitCode, serializer);
    sse_encode_String(self.cwd, serializer);
    sse_encode_bool(self.hadMarker, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_connection_input(
    ConnectionInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_connection_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_system_stats_dto(
    SystemStatsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_system_stats_dto(self, serializer);
  }

  @protected
  void sse_encode_connection_dto(ConnectionDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.protocol, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.folder, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.authMethod, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_bool(self.hasPassword, serializer);
    sse_encode_bool(self.hasPrivateKeyPath, serializer);
    sse_encode_bool(self.hasPassphrase, serializer);
  }

  @protected
  void sse_encode_connection_input(
    ConnectionInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.protocol, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.authMethod, serializer);
    sse_encode_String(self.folder, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_String(self.password, serializer);
    sse_encode_opt_String(self.privateKeyPath, serializer);
    sse_encode_opt_String(self.passphrase, serializer);
  }

  @protected
  void sse_encode_disk_usage_dto(DiskUsageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mount, serializer);
    sse_encode_i_64(self.usedKb, serializer);
    sse_encode_i_64(self.totalKb, serializer);
    sse_encode_f_64(self.percent, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_connection_dto(
    List<ConnectionDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_connection_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_disk_usage_dto(
    List<DiskUsageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_disk_usage_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mcp_tool_dto(
    List<McpToolDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mcp_tool_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sftp_entry_dto(
    List<SftpEntryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sftp_entry_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_mcp_status_dto(McpStatusDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.running, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.endpoint, serializer);
    sse_encode_u_64(self.uptimeSecs, serializer);
    sse_encode_u_32(self.toolCount, serializer);
  }

  @protected
  void sse_encode_mcp_tool_dto(McpToolDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_String(self.category, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_system_stats_dto(
    SystemStatsDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_system_stats_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_sftp_entry_dto(SftpEntryDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_i_64(self.size, serializer);
    sse_encode_String(self.permissions, serializer);
    sse_encode_i_64(self.modifiedUnix, serializer);
  }

  @protected
  void sse_encode_stats_frame(StatsFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_system_stats_dto(self.sample, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_system_stats_dto(
    SystemStatsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.cpuPercent, serializer);
    sse_encode_f_64(self.memPercent, serializer);
    sse_encode_i_64(self.memUsedKb, serializer);
    sse_encode_i_64(self.memTotalKb, serializer);
    sse_encode_f_64(self.swapPercent, serializer);
    sse_encode_i_64(self.swapUsedKb, serializer);
    sse_encode_i_64(self.swapTotalKb, serializer);
    sse_encode_f_64(self.diskPercent, serializer);
    sse_encode_i_64(self.diskUsedKb, serializer);
    sse_encode_i_64(self.diskTotalKb, serializer);
    sse_encode_list_disk_usage_dto(self.disks, serializer);
    sse_encode_f_64(self.netRxPerSec, serializer);
    sse_encode_f_64(self.netTxPerSec, serializer);
    sse_encode_f_64(self.load1, serializer);
    sse_encode_f_64(self.uptimeSecs, serializer);
    sse_encode_u_32(self.cpuCores, serializer);
    sse_encode_String(self.os, serializer);
  }

  @protected
  void sse_encode_transfer_progress(
    TransferProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.transferred, serializer);
    sse_encode_i_64(self.total, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
