// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/adb.dart';
import 'api/blockterm.dart';
import 'api/connections.dart';
import 'api/mcp.dart';
import 'api/monitor.dart';
import 'api/sftp.dart';
import 'api/simple.dart';
import 'api/terminal.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<StatsFrame> dco_decode_StreamSink_stats_frame_Sse(dynamic raw);

  @protected
  RustStreamSink<TransferProgress> dco_decode_StreamSink_transfer_progress_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BlockResultDto dco_decode_block_result_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ConnectionInput dco_decode_box_autoadd_connection_input(dynamic raw);

  @protected
  SystemStatsDto dco_decode_box_autoadd_system_stats_dto(dynamic raw);

  @protected
  ConnectionDto dco_decode_connection_dto(dynamic raw);

  @protected
  ConnectionInput dco_decode_connection_input(dynamic raw);

  @protected
  DiskUsageDto dco_decode_disk_usage_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ConnectionDto> dco_decode_list_connection_dto(dynamic raw);

  @protected
  List<DiskUsageDto> dco_decode_list_disk_usage_dto(dynamic raw);

  @protected
  List<McpToolDto> dco_decode_list_mcp_tool_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SftpEntryDto> dco_decode_list_sftp_entry_dto(dynamic raw);

  @protected
  McpStatusDto dco_decode_mcp_status_dto(dynamic raw);

  @protected
  McpToolDto dco_decode_mcp_tool_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  SystemStatsDto? dco_decode_opt_box_autoadd_system_stats_dto(dynamic raw);

  @protected
  SftpEntryDto dco_decode_sftp_entry_dto(dynamic raw);

  @protected
  StatsFrame dco_decode_stats_frame(dynamic raw);

  @protected
  SystemStatsDto dco_decode_system_stats_dto(dynamic raw);

  @protected
  TransferProgress dco_decode_transfer_progress(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<StatsFrame> sse_decode_StreamSink_stats_frame_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TransferProgress> sse_decode_StreamSink_transfer_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BlockResultDto sse_decode_block_result_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ConnectionInput sse_decode_box_autoadd_connection_input(
    SseDeserializer deserializer,
  );

  @protected
  SystemStatsDto sse_decode_box_autoadd_system_stats_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConnectionDto sse_decode_connection_dto(SseDeserializer deserializer);

  @protected
  ConnectionInput sse_decode_connection_input(SseDeserializer deserializer);

  @protected
  DiskUsageDto sse_decode_disk_usage_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ConnectionDto> sse_decode_list_connection_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DiskUsageDto> sse_decode_list_disk_usage_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<McpToolDto> sse_decode_list_mcp_tool_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SftpEntryDto> sse_decode_list_sftp_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  McpStatusDto sse_decode_mcp_status_dto(SseDeserializer deserializer);

  @protected
  McpToolDto sse_decode_mcp_tool_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  SystemStatsDto? sse_decode_opt_box_autoadd_system_stats_dto(
    SseDeserializer deserializer,
  );

  @protected
  SftpEntryDto sse_decode_sftp_entry_dto(SseDeserializer deserializer);

  @protected
  StatsFrame sse_decode_stats_frame(SseDeserializer deserializer);

  @protected
  SystemStatsDto sse_decode_system_stats_dto(SseDeserializer deserializer);

  @protected
  TransferProgress sse_decode_transfer_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_stats_frame_Sse(
    RustStreamSink<StatsFrame> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_transfer_progress_Sse(
    RustStreamSink<TransferProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_block_result_dto(
    BlockResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_connection_input(
    ConnectionInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_system_stats_dto(
    SystemStatsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_dto(ConnectionDto self, SseSerializer serializer);

  @protected
  void sse_encode_connection_input(
    ConnectionInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_disk_usage_dto(DiskUsageDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_connection_dto(
    List<ConnectionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_disk_usage_dto(
    List<DiskUsageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mcp_tool_dto(
    List<McpToolDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sftp_entry_dto(
    List<SftpEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mcp_status_dto(McpStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_mcp_tool_dto(McpToolDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_system_stats_dto(
    SystemStatsDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sftp_entry_dto(SftpEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_stats_frame(StatsFrame self, SseSerializer serializer);

  @protected
  void sse_encode_system_stats_dto(
    SystemStatsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_progress(
    TransferProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
